from __future__ import annotations

import asyncio
import hashlib
from collections.abc import AsyncIterator
from pathlib import Path

from athenaeum.loops import DeterministicLoopEngine
from athenaeum.loops.context import RunContext
from athenaeum.schemas import (
    CitationRef,
    ClaimRef,
    CourtOpinion,
    EvolveCandidate,
    EvolveOutput,
    ReportOutput,
    ReviewOutput,
    ScienceOutput,
    Verdict,
)

from .cli import RuntimeDefinition
from .models import AgentEvent, AgentResult, AgentTask, CostDelta, RuntimeHealth, RuntimeMeta, Workspace


class MinimalRuntime:
    name = "minimal"
    definition = RuntimeDefinition(
        name="minimal",
        binary="python",
        args=("in-process", "deterministic"),
        aliases=("stub", "local"),
        fix=None,
    )

    def health(self) -> RuntimeHealth:
        return RuntimeHealth(
            name=self.name,
            binary="in-process",
            available=True,
            version="deterministic minimal runtime",
            auth_ok=True,
        )

    async def spawn(self, task: AgentTask, workspace: Workspace) -> AsyncIterator[AgentEvent]:
        workspace.root.mkdir(parents=True, exist_ok=True)
        payload = task.input_payload
        run_id = str(payload.get("run_id") or _stable_id(task.prompt, payload.get("seed", 0)))[:8]
        artifact_root = Path(str(payload.get("artifact_root") or workspace.root))
        phases = ("research", "debate", "draft", "verify", "court", "revise")
        for phase in phases:
            await asyncio.sleep(0)
            yield AgentEvent(kind="progress", message=f"{phase} complete", raw={"node": phase, "state": "done"})
        context = RunContext(
            question=str(payload.get("question") or task.prompt),
            run_id=run_id,
            effort=str(payload.get("effort") or "high"),
            mode=str(payload.get("mode") or "auto"),
            audience=payload.get("audience"),
            seed=int(payload.get("seed") or 0),
            artifact_root=artifact_root,
        )
        report = DeterministicLoopEngine(context).run_auto()
        yield AgentEvent(
            kind="final",
            result=AgentResult(
                content=report.model_dump(mode="json"),
                claims=report.claims,
                citations=report.citations,
                confidence=0.55,
                cost=CostDelta(tokens_in=0, tokens_out=0, usd=0.0),
                runtime_meta=RuntimeMeta(runtime=self.name, model="deterministic-minimal"),
            ),
        )


def build_report_output(
    question: str,
    run_id: str | None = None,
    effort: str = "high",
    mode: str = "auto",
    audience: str | None = None,
    seed: int = 0,
) -> ReportOutput:
    rid = run_id or _stable_id(question, seed)[:8]
    citation = CitationRef(
        id="spec-think-tank",
        title="ATHENAEUM technical specification",
        source_type="spec",
        quote="Deterministic orchestration with typed runtime outputs.",
    )
    claims = [
        ClaimRef(
            id=f"claim-{_stable_id(question, seed)[:6]}",
            text="This report was generated by the deterministic minimal ATHENAEUM runtime.",
            status="verified",
            citation_ids=[citation.id],
            confidence=1.0,
        ),
        ClaimRef(
            id=f"claim-{_stable_id(question, effort)[:6]}",
            text="No live web or model research was performed in minimal mode.",
            status="verified",
            citation_ids=[citation.id],
            confidence=1.0,
        ),
        ClaimRef(
            id=f"claim-{_stable_id(question, mode)[:6]}",
            text="Substantive domain conclusions remain unverified until an API or CLI runtime performs research.",
            status="unverified",
            citation_ids=[],
            confidence=0.35,
        ),
    ]
    audience_line = f"Audience: {audience}." if audience else "Audience: educated generalist."
    summary = (
        f"Minimal mode compiled the ATHENAEUM workflow for '{question}' and produced a "
        "schema-valid scaffold report without external model calls."
    )
    markdown = "\n".join(
        [
            f"# ATHENAEUM Report: {question}",
            "",
            f"Run: `{rid}`  ",
            f"Mode: `{mode}`  ",
            f"Effort: `{effort}`  ",
            audience_line,
            "",
            "## Executive Summary",
            summary,
            "",
            "## Current Position",
            "The safe minimal answer is a structured starting point, not a researched final judgment. "
            "It preserves the report shape, claim ledger, citation list, and reviewer court fields so "
            "the same output contract can be used by richer runtimes.",
            "",
            "## Claim Ledger",
            *[f"- `{claim.status}` {claim.text}" for claim in claims],
            "",
            "## Citations",
            f"- [{citation.id}] {citation.title}. {citation.quote}",
        ]
    )
    return ReportOutput(
        title=f"ATHENAEUM Report: {question}",
        question=question,
        summary=summary,
        report_markdown=markdown,
        claims=claims,
        citations=[citation],
        court=CourtOpinion(score_before=5.0, score_after=5.5, blockers=0, major_findings=1),
        run_id=rid,
    )


def build_evolve_output(prompt: str, generations: int, axes: list[str], seed: int = 0) -> EvolveOutput:
    archive: list[EvolveCandidate] = []
    for index in range(1, min(generations, 5) + 1):
        axis_values = {axis: _axis_value(prompt, axis, index, seed) for axis in axes}
        archive.append(
            EvolveCandidate(
                id=f"elite-{index}",
                thesis=f"Candidate {index}: {prompt} through a {axis_values.get(axes[0], 'balanced')} lens.",
                axes=axis_values,
                fitness=round(5.0 + index * 0.6, 2),
                strongest_objection="Needs external evidence before promotion beyond minimal mode.",
                repair="Route through research, verify, and court loops with non-minimal runtimes.",
            )
        )
    markdown = "\n".join(
        [f"# Evolve Archive: {prompt}", "", f"Generations: {generations}", "", "## Elites"]
        + [f"- `{item.id}` fitness {item.fitness}: {item.thesis}" for item in archive]
    )
    return EvolveOutput(prompt=prompt, generations=generations, axes=axes, archive=archive, report_markdown=markdown)


def build_review_output(source_path: str, draft: str, court: str, audience: str | None = None) -> ReviewOutput:
    words = len(draft.split())
    verdicts = [
        Verdict(
            reviewer="argument",
            severity="minor" if words else "major",
            section_anchor="document",
            finding="Minimal review completed without external evidence tools.",
            evidence=f"The submitted draft has {words} words.",
            suggested_fix="Run with a non-minimal runtime for full court review.",
            confidence=0.7,
        )
    ]
    opinion = CourtOpinion(score_before=6.0, score_after=6.2, blockers=0, major_findings=0, verdicts=verdicts)
    markdown = "\n".join(
        [
            f"# Review: {Path(source_path).name}",
            "",
            f"Court: `{court}`",
            f"Audience: {audience or 'educated generalist'}",
            "",
            "## Findings",
            *[f"- `{verdict.severity}` {verdict.finding} {verdict.evidence}" for verdict in verdicts],
        ]
    )
    return ReviewOutput(source_path=source_path, audience=audience, court=opinion, report_markdown=markdown)


def build_science_output(hypothesis: str, sandbox: str, max_experiments: int) -> ScienceOutput:
    verdict = Verdict(
        reviewer="methods",
        severity="major",
        section_anchor="methods",
        finding="Science mode is scaffolded but does not execute experiments in minimal mode.",
        evidence="No sandbox commands were run.",
        suggested_fix="Use Codex or Claude runtime with an explicit sandbox policy for execution.",
        confidence=0.9,
    )
    markdown = "\n".join(
        [
            f"# Science Plan: {hypothesis}",
            "",
            f"Sandbox: `{sandbox}`",
            f"Max experiments: {max_experiments}",
            "",
            "## Methods Gate",
            f"- `{verdict.severity}` {verdict.finding}",
        ]
    )
    return ScienceOutput(
        hypothesis=hypothesis,
        sandbox=sandbox,
        max_experiments=max_experiments,
        stage="planned",
        methods_gate=[verdict],
        report_markdown=markdown,
    )


def _stable_id(*parts: object) -> str:
    raw = "|".join(str(part) for part in parts)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _axis_value(prompt: str, axis: str, index: int, seed: int) -> str:
    values = {
        "novelty": ("conventional", "adjacent", "heterodox"),
        "risk": ("conservative", "balanced", "aggressive"),
        "horizon": ("near", "mid", "far"),
    }.get(axis, ("low", "medium", "high"))
    offset = int(_stable_id(prompt, axis, seed)[:2], 16)
    return values[(offset + index) % len(values)]
